### ISSUE TITLE
Install as hugo module?

### ISSUE THREAD

**Issue by danipoloni** [apvarun/digital-garden-hugo-theme#21]
Hey, I like this theme quite a lot, but suggested way of installation and running is quite an annoyance. Aren't you thinking about supporting installation as a hugo module? For example Blowfish theme (with tailwind as well) works as a module just fine, whilst Digital Garden looses all styles.

**Comment by apvarun** [comment]
I believe this happens because Blowfish precompiles the styles for the site. This seemed pretty unintuitive but looking at the number of people having issues, maybe its better to have to precompiled and have an option to rebuild css if needed. I will update this. PS: hugo module is not required for this.
